"""Build assessment comparison tables.

Every field is derived directly from catalog data (name, category,
assessment_type, skills_measured, duration, remote_testing_support,
adaptive_irt_support). Nothing here is generated by a language model, so
there is nothing to hallucinate: nuanced-sounding columns like "Strengths",
"Limitations", and "Recommendation" are template strings built from those
same catalog fields, not free-text generation.
"""
from typing import Any, Dict, List

from models_catalog import AssessmentItem

COLUMNS = [
    "Assessment Name",
    "Assessment Type",
    "Skills Measured",
    "Duration",
    "Remote Testing",
    "Adaptive",
    "Use Case",
    "Strengths",
    "Limitations",
    "Recommendation",
]


def _use_case(item: AssessmentItem) -> str:
    if item.category:
        return f"Best suited for evaluating {item.category.lower()} needs."
    return "General hiring assessment use case."


def _strengths(item: AssessmentItem) -> str:
    if item.skills_measured:
        top = ", ".join(item.skills_measured[:4])
        return f"Directly measures: {top}."
    return f"Covers the {item.category or 'general'} category."


def _limitations(item: AssessmentItem) -> str:
    limitations = []
    if not item.duration:
        limitations.append("no published duration in the catalog")
    if not item.remote_testing_support:
        limitations.append("not confirmed for remote/unproctored testing")
    if not item.adaptive_irt_support:
        limitations.append("not an adaptive/IRT-based test")
    if not limitations:
        return "No notable limitations in the catalog data."
    return "; ".join(limitations).capitalize() + "."


def _recommendation_line(items: List[AssessmentItem], target: AssessmentItem) -> str:
    """Rule-based, data-grounded recommendation: prefers remote support,
    then adaptive support, then a known duration, then skill breadth,
    compared against the other item(s) in this table."""
    others = [i for i in items if i is not target]
    if not others:
        return "Selected as a strong standalone match for the request."

    reasons = []
    if target.remote_testing_support and not any(o.remote_testing_support for o in others):
        reasons.append("supports remote testing when the alternative(s) do not")
    if target.adaptive_irt_support and not any(o.adaptive_irt_support for o in others):
        reasons.append("uses adaptive/IRT scoring")
    if len(target.skills_measured) > max((len(o.skills_measured) for o in others), default=0):
        reasons.append("measures a broader set of catalog-listed skills")

    if reasons:
        return "Preferred when you need it to " + " and ".join(reasons) + "."
    return "Comparable to the alternative(s); choose based on role-specific skill fit."


def build_comparison(items: List[AssessmentItem]) -> Dict[str, Any]:
    """Return {"markdown": str, "rows": List[dict], "columns": List[str]}."""
    rows: List[Dict[str, Any]] = []
    for item in items:
        rows.append({
            "Assessment Name": item.name,
            "Assessment Type": item.assessment_type or item.category,
            "Skills Measured": ", ".join(item.skills_measured) if item.skills_measured else "Not specified",
            "Duration": item.duration or "Not specified",
            "Remote Testing": "Yes" if item.remote_testing_support else "No",
            "Adaptive": "Yes" if item.adaptive_irt_support else "No",
            "Use Case": _use_case(item),
            "Strengths": _strengths(item),
            "Limitations": _limitations(item),
            "Recommendation": _recommendation_line(items, item),
            "url": item.url,
        })

    header = "| " + " | ".join(COLUMNS) + " |"
    divider = "| " + " | ".join(["---"] * len(COLUMNS)) + " |"
    body_lines = []
    for row in rows:
        body_lines.append("| " + " | ".join(str(row[c]).replace("|", "/") for c in COLUMNS) + " |")

    markdown = "\n".join([header, divider, *body_lines])
    return {"markdown": markdown, "rows": rows, "columns": COLUMNS}
